site_name: Documentations
site_url: https://alexandrezlima.github.io/documentations/


nav:
    - Home: index.md
    - Lock-on: LockOn.md

theme: 
  name: readthedocs
  prev_next_buttons_location: bottom